### PR TITLE
Targets - refactoring targets to be better sizes & less brittle

### PR DESCRIPTION
**Pull request by lindsayplatt**
In response to #4, I combined a few targets and split others apart. I resisted the urge to use a task plan to download the data for each site and then combine since I assume that is taught in a later course 😉

### CODE REVIEW

**Review by aappling-usgs — APPROVED** [review]
I don't love that `combine_data` is the name for a function that does more than just combine data (it also renames and selects columns)...but I also can't think of a name that's more precise while staying concise, so I guess I'll have to live with it. =)

Everything else looks great!

**Comment by lindsayplatt** [comment]
How important is conciseness? Even though it may be longer, I could use `combine_and_process` to clearly show that this fxn does more than just combine

**Comment by aappling-usgs** [comment]
:+1:, `combine_and_process` would work. I'm good with preferring precise to concise.

**Comment by lindsayplatt** [comment]
Do I merge this myself now that it has been approved or wait for you to merge?

**Comment by aappling-usgs** [comment]
Oh - either way. I'll merge now.

**Pull request merged**
